### ISSUE TITLE
구경 잘하고 갑니당! 👍 

### ISSUE THREAD

**Issue by sparta-jason** [hj2bf/Advanced_Blog_Node.js#1]
잘 보고 갑니다 작게나마 의견 공유드려요 ㅎ_ㅎ..
1. 게시글 및 댓글 작성 후 출력 시 줄 띄운 것도 적용되면 좋을 것 같아요!
2. 패스워드가 닉네임에 포함되어있는 경우 유효성 체크 확인해보시면 좋을 것 같아요. 아래 처럼 가입이 되네용!
nickname : asdasd123
pw : asdasd

한 주간 고생 많으셨어요 앞으로도 같이 파이팅합시다!

**Comment by hj2bf** [comment]
넵 감사합니다! 해결하도록 하겠습니다!! 

화이팅해요!!~~
